SELECT ROUND(AVG(DAILY_FEE),0) ASAVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV'


# SELECT ROUND(AVG(car.DAILY_FEE),0) AS AVERAGE_FEE
# FROM CAR_RENTAL_COMPANY_CAR as car
# WHERE car.CAR_TYPE = 'SUV'