SELECT third.ID AS ID
FROM ECOLI_DATA AS fir
LEFT JOIN ECOLI_DATA AS second ON fir.ID = second.PARENT_ID
INNER JOIN ECOLI_DATA AS third ON second.ID = third.PARENT_ID
WHERE fir.PARENT_ID IS NULL AND second.ID IS NOT NULL
ORDER BY ID