SELECT third.ID
FROM ECOLI_DATA as first
LEFT JOIN ECOLI_DATA as second ON first.ID = second.PARENT_ID
LEFT JOIN ECOLI_DATA as third ON second.ID = third.PARENT_ID
WHERE first.PARENT_ID IS NULL AND second.ID IS NOT NULL AND third.ID IS NOT NULL
ORDER BY third.ID ASC
















# SELECT third.ID AS ID
# FROM ECOLI_DATA AS fir
# LEFT JOIN ECOLI_DATA AS second ON fir.ID = second.PARENT_ID
# INNER JOIN ECOLI_DATA AS third ON second.ID = third.PARENT_ID
# WHERE fir.PARENT_ID IS NULL AND second.ID IS NOT NULL
# ORDER BY ID