SELECT ii.ITEM_ID,
        ii.ITEM_NAME,
        ii.RARITY
FROM ITEM_INFO as ii 
JOIN ITEM_TREE as it
ON ii.ITEM_ID = it.ITEM_ID
WHERE PARENT_ITEM_ID in (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY ='RARE')
ORDER BY ITEM_ID DESC