SELECT ITEM_ID,
        ITEM_NAME,
        RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN(
    SELECT tree.ITEM_ID
    FROM ITEM_INFO as info
    LEFT JOIN ITEM_TREE tree
      ON info.ITEM_ID = tree.PARENT_ITEM_ID
    WHERE tree.ITEM_ID IS NOT NULL 
      AND info.RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC;












# SELECT ii.ITEM_ID,
#         ii.ITEM_NAME,
#         ii.RARITY
# FROM ITEM_INFO as ii 
# JOIN ITEM_TREE as it
# ON ii.ITEM_ID = it.ITEM_ID
# WHERE PARENT_ITEM_ID in (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY ='RARE')
# ORDER BY ITEM_ID DESC