-- 코드를 작성해주세요
SELECT le.ID,
        le.GENOTYPE,
        re.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS le 
LEFT JOIN ECOLI_DATA AS re
ON le.PARENT_ID = re.ID
WHERE le.GENOTYPE & re.GENOTYPE = re.GENOTYPE
ORDER BY le.ID ASC

