SELECT ced.ID,
        ced.GENOTYPE,
        ped.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA as ped
JOIN ECOLI_DATA as ced
ON ped.ID = ced.PARENT_ID
WHERE ped.GENOTYPE & ced.GENOTYPE = ped.GENOTYPE
ORDER BY ced.ID ASC









# SELECT *
# FROM ECOLI_DATA AS le 
# LEFT JOIN ECOLI_DATA AS re
# ON le.PARENT_ID = re.ID
# WHERE le.GENOTYPE & re.GENOTYPE = re.GENOTYPE
# ORDER BY le.ID ASC