SELECT fi.ID,
        fni.FISH_NAME,
        fi.LENGTH
FROM (
    SELECT ID,
            FISH_TYPE,
            LENGTH,
            RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) as ra
    FROM FISH_INFO
)as fi 
JOIN FISH_NAME_INFO as fni
ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE fi.ra = 1
ORDER BY 1



# SELECT ID,
#         FISH_NAME,
#         LENGTH
# FROM FISH_INFO as fi
# JOIN FISH_NAME_INFO as fni
#   ON fi.FISH_TYPE = fni.FISH_TYPE
# WHERE fi.LENGTH IS NOT NULL AND
# FI.LENGTH = (
#   SELECT MAX(FI2.LENGTH)
#   FROM FISH_INFO FI2
#   WHERE FI.FISH_TYPE = FI2.FISH_TYPE
# )
# ORDER BY ID