SELECT fi.ID,
       fni.FISH_NAME,
       fi.LENGTH AS LENGTH
FROM FISH_INFO AS fi 
LEFT JOIN FISH_NAME_INFO AS fni
ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE fi.LENGTH IS NOT NULL
  AND fi.LENGTH = (
        SELECT MAX(LENGTH) 
        FROM FISH_INFO 
        WHERE FISH_TYPE = fi.FISH_TYPE
    );